### ISSUE TITLE
WITH is not correctly handled

### ISSUE THREAD

**Issue by ybastide** [David-Wobrock/sqlvalidator#26]
Hi David :wave:,
```sql
select *
from
(
    with t as (
        select 1 foo
    )
    select *
    from t
)
```

Is translated
```sql
SELECT *
FROM (
 with t
)
```

**Comment by David-Wobrock** [comment]
Wasn't too hard to add it.
I hope it will work for most cases (and yours obviously) :)

See https://github.com/David-Wobrock/sqlvalidator/blob/38581286e9cab5aed0525136e74970a676e45c62/tests/integration/test_formatting.py#L2038-L2127
