### ISSUE TITLE
Quote in double Quote -> Error.

### ISSUE THREAD

**Issue by syndrael** [David-Wobrock/sqlvalidator#29]
Hello,
Here are two examples, first one works
not the second.
both are accepted by the database (Hive)

test= "select     col1,     dc_ip     from table     where 1 = 1     and col1 IN (**\'Example 1\', \'Example \'2\'**)     order by col2 desc     limit 20"
print(test)
sql_query = sqlvalidator.parse(test)
print(sql_query.is_valid())

test= "select     col1,     dc_ip     from table     where 1 = 1     and col1 IN (**\"Example 1\", \"Example \'2\"**)     order by col2 desc     limit 20"
print(test)
sql_query = sqlvalidator.parse(test)
print(sql_query.is_valid())

I thank you for your help.
Regards

**Comment by David-Wobrock** [comment]
Hi @syndrael , thanks for submitting an issue.
I'll look into into this issue once I find some time :)
