### ISSUE TITLE
Are you accepting PRs

### ISSUE THREAD

**Issue by RiccardoTonini** [David-Wobrock/sqlvalidator#3]
Are you accepting PRs on this project?

**Comment by David-Wobrock** [comment]
Hi @RiccardoTonini 
Well, I don't know yet, but why not :) The project is still very early, so I still break APIs from time to time, a lot of things are changing and I'm basically extending support and features to the ones I currently need. But I try to work on it when I have some time.

However, I'm also not 100% certain of the direction the project should take.

So, of course patches and suggestions are welcome, but I cannot garantee that will be merged as they are :)

I'm very happy that you take interest in the project. What are the kind of things/features that you'd like to see?

**Comment by RiccardoTonini** [comment]
Hi,

thank for replaying so promptly.
I haven't got any specific feature suggestion at the moment.
However I have found a little issue in the validation and can open a PR with some tests and a possible approach.
Thanks

**Comment by David-Wobrock** [comment]
Sure! The validation is very early stage and still brittle, and I'm more focusing on the parsing and formatting aspect for now.
Feel free to open a PR, I'd be happy to review and merge it

**Comment by RiccardoTonini** [comment]
Hi,

I've added a PR: https://github.com/David-Wobrock/sqlvalidator/pull/4
Let me know what you think.

**Comment by David-Wobrock** [comment]
Thanks for the PR! I responded over there.
Closing this issue for now, we can pursue the discussion there :)
